sonar.projectKey=Mcc-Mak_hk-tour-guide
sonar.organization=mcc-mak
sonar.projectName=hk-tour-guide
sonar.sources=codebase,.crewai
sonar.exclusions=**/__pycache__/**,**/_stubs/**,**/site-packages/**
sonar.python.version=3.12
